project:
  type: website
  output-dir: docs
  
website:
  title: "test"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/YOURUSERNAME/YOURREPO
  page-footer:
    right: "test"
    left: "test"

format:
  html:
    theme: cerulean
    toc: true

editor: source

